### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fabianmossberg** [SeteMares/vue-mapkit#1]
I've follower the instructions, but I can't figure out how to actually draw a map.

> Now you can draw a map in a component.

and

> // use `map` to perform any changes

I'm not sure how to make it draw a map. I have tried my JWT and i can create a map using html and js, but not with this component.

**Comment by progand** [comment]
Hi! 
Map is being created by `createMapkit(mapId, options)` function. You need to add element where you want to draw a map. The element nust have some `id` html attribute. All you need to do is to pass this `id` as first parameter to `createMapkit`.
I've updated documentation, please check it again. https://github.com/SeteMares/vue-mapkit#draw-a-map
